### ISSUE TITLE
`ts-parse` with customized format string

### ISSUE THREAD

**Issue by jcguu95** [alphapapa/ts.el#19]
This is a feature request; I'm happy to implement if it's approved.

### Problem

While `#'ts-format` supports customized format string, the parser `#'ts-parse` does not. For example,

```
(let ((format-string "%Y%m%d-%H%M%S-%z"))
  (ts-format format-string)) ;; => "20210720-034335--0500"
```

In a project where the author wishes to use the same `format-string` throughout, it makes sense to have `ts.el` be able to parse it back. **However, the main parser `ts-parse` does not support customized format string.** Instead, it relies on the internal `parse-time-string`, which doesn't seem to support customized format string either.

### Suggestion

+ Rewrite `ts-parse` so that it supports customized format string.
+ If my proposal makes sense, I can make a PR.

**Comment by alphapapa** [comment]
Hi,

This library is mostly intended as a slightly enhanced, thin wrapper around Emacs's built-in date/time facilities.  With the new date/time-relatedfunctions in Emacs 27, this library should probably try to become an even thinner wrapper than it is now.  So I'd prefer that `ts-parse` remain a thin wrapper around `parse-time-string`.

If you need fully custom parsing, I'd be willing to consider it as a separate function (maybe it could be called `ts-parse*` for conciseness), depending on how much code it requires.  But before doing that, it would probably be best to propose a patch to add such a function to Emacs itself.  If that were rejected, we could consider doing it here; or if it were approved, we could consider also adding it here temporarily, since old Emacs versions exist in the wild for a while, but in that case, it might be better suited as an in-tree ELPA package.

What do you think?  Thanks.

**Comment by jcguu95** [comment]
I see your concern. Indeed, there seems to be no short way to do that, mainly because while formatting "loses information", parsing needs to "restore information", which can be done only with some extra assumptions. The assumptions should be encoded into a DSL. For example, we need something like

```
(parse! "210107-235143" "%2Y%2m%2d-%2H%2M%2S") ;; => (43 51 23 7 1 2021)
```

Without a well-defined DSL, `"210107"` may well be parsed as `2007-January-21`. I will do more research on this, and see if a patch can be sent to emacs. Before that, let me close the issue for the time being. Thanks again!

**Comment by alphapapa** [comment]
Sure.  Here are a few more thoughts:

* You may find the code in this library instructive or inspiring; it's very comprehensive: https://github.com/emacs-php/emacs-datetime
* Defining a custom parser using `%`-based specs seems similar to defining custom formatter specs, so you may find this helpful: https://github.com/alphapapa/ement.el/blob/387e55d39bc67ee78c00c92a6dcca42107a4bf37/ement-room.el#L611  It uses code from `format-spec`, which is built-in to Emacs, along with a macro I wrote to make defining formatters within the function easier.

**Comment by jcguu95** [comment]
Just came up with a better and easier idea: instead of using a DSL that's doom to be degenerated, why not just use sexprs? The single function below solves my need. Please let me know if you want this (or some modified version) to be in `ts-parse`.

```
(require 'ht)

(defun my/parse (directives str)
  (flet ((parse-step (directive str ht)
                     (if (atom directive)
                         (if (string-match (format "^%s" directive) str)
                             (substring str (length directive))
                           (error "Parsing failure~ directive: %s; str: %s." directive str))
                       (let* ((key (car directive))
                              (int (car (cdr directive)))
                              (to-parse (substring str 0 int)))
                         ;; TODO For natural lang, replace
                         ;; parse-integer by any customized
                         ;; transformers.
                         (ht-set! ht key (cl-parse-integer to-parse))
                         (substring str int)))))
    (let ((result (ht-create)))
      (while (not (equal str ""))
        (setf str (parse-step (pop directives) str result)))
      result)))

(defvar my/default-format
  '((:year 4) (:month 2) (:day 2) "-"
    (:hour 2) (:minute 2) (:second 2)))

(my/parse my/default-format "20200718-201504")
;; => #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
;;                   (:year 2020 :month 7 :day 18 :hour 20 :minute 15 :second 4))
```

**Comment by jcguu95** [comment]
(Open again to ask if `ts.el` needs such functionality.)

**Comment by alphapapa** [comment]
That's pretty cool, concise and flexible.  Here are a few thoughts:

* A hash table is probably overkill for this, and probably will perform worse than, e.g. an alist.  AFAIK alists in Emacs generally outperform hash tables until the size reaches some tens of elements.  (I don't remember if I've addressed this specific issue here, but I try to collect some info about optimization in Emacs here: https://github.com/alphapapa/emacs-package-dev-handbook)
* Rather than using `substring`, which I guess will allocate a new string every time, you could do it more idiomatically by using a buffer and advancing the point within it.  Although you might want to benchmark it to see which is actually more efficient.
* I see the to-do item there.  For a general implementation, it would probably need to handle non-numeric parts of timestamps.
* It would be helpful if the docstring were written primarily in terms of what result is returned by the function.  I read the whole thing, and I'm still not clear what exactly it returns--a hash table, I guess, but I don't understand what a hash table has to do with a timestamp.  :)

As to whether this belongs in this library: I don't know.  I'm not opposed to it, on principle, but at the same time, I'm generally hesitant to add features unless they're needed.  Of course, if I needed this in a package of mine, I'd probably be more enthusiastic.  ;)  But from a long-term perspective, as the maintainer of a library, any feature I add is one that I'm committing to maintain, and maintaining a feature I don't currently use can be an extra burden.

So I'd probably prefer not to add this feature now.  I'd rather wait until it's clear that it's generally needed by Emacs packages; and if that is so, I'd want to consider whether this library were the best place to put it, rather than, e.g. in Emacs itself.  And I'd want it to fully support all timestamp-like features, as well, like non-numeric parts, time zones, etc.

What do you think?  Thanks.

**Comment by jcguu95** [comment]
Makes sense! I will see if Emacs takes it first. Thanks for your other comments too :)
