### ISSUE TITLE
make-ts using only year, month and day 

### ISSUE THREAD

**Issue by whudwl** [alphapapa/ts.el#28]
The code below echoes current date an time instead 2024-02-03, is this normal?   

``` lisp 
(let ((myts (make-ts :year 2024 :month 2 :day 3)))
  (ts-format myts))
```

**Comment by alphapapa** [comment]
This would seem to fall into the category of "undefined behavior."  If you also specify the hour, minute, and second, it will work as desired.

You can see the relevant code here: https://github.com/alphapapa/ts.el/blob/552936017cfdec89f7fc20c254ae6b37c3f22c5b/ts.el#L226-L230

When any of those fields are not given, `float-time` is called without argument, which returns the current time.  This is probably not ideal, but it's not clear what the user intended, nor what would be best if various fields were unspecified.

OTOH, `parse-time-string` already has some logic for this, e.g. `(ts-format (ts-parse "2024-02-03"))` prints `"2024-02-03 00:00:00 -0600"`, and it's more concise, anyway.  So probably you should eschew `make-ts` and consider `ts-now` and `ts-parse` to be higher-level APIs.

Be advised that, in general, if a timestamp is important, you should probably always verify the details anyway, because date/time-related code is hard and has many edge cases.

**Comment by whudwl** [comment]
Thank you very much for your explaination.  
I really appreciate it!
